      PROGRAM UMAT_TESTER
      INCLUDE 'ABA_PARAM.INC'
C
C     COPYRIGHT (2011) EVER J. BARBERO, ALL RIGHTS RESERVED
C
!     PROGRAM TO TEST A UMAT BEFORE USING IT INSIDE ABAQUS
            
!     PARAMETERS FOR THE TYPE OF UMAT
!     TRUSS
      PARAMETER (NDI=1, NSHR=0, NTENS=NDI+NSHR)
!     PLANE STRESS      
!      PARAMETER (NDI=2, NSHR=1, NTENS=NDI+NSHR)
!     3D SOLID
!      PARAMETER (NDI=3, NSHR=3, NTENS=NDI+NSHR)

!     ENTER HERE THE NUMBER OF PROPERTIES AND NUMBER OF STATE VARIABLES FOR YOUR PROBLEM
!     EX 8.3
      PARAMETER (NPROPS=3, NSTATV=2)  
!     TSAIW
!      PARAMETER (NPROPS=11, NSTATV=2)  
!     VISCO 3D
!      PARAMETER (NPROPS=10, NSTATV=NTENS)  !strain components
      
      DIMENSION STRESS(NTENS),STATEV(NSTATV),
     & DDSDDE(NTENS,NTENS),DDSDDT(NTENS),DRPLDE(NTENS),
     & STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     & PROPS(NPROPS),COORDS(3),DROT(3,3),
     & DFGRD0(3,3),DFGRD1(3,3)
     
      CHARACTER*80 MATERL
      CHARACTER*72 STRING72
      PARAMETER (MATERL = 'WHATEVER MATERIAL YOU WANT TO DO')

!     YOUR TESTER EXECUTABLE STATEMENTS START HERE
      WRITE(6,"(/'NDI, NSHR, NPROPS, NSTATEV')")
      WRITE(6,"(4I10)") NDI, NSHR, NPROPS, NSTATV
      
C	NDI: # of direct components (11,...) of DDSDDE, DDSDDT, and DRPLDE
C	NSHR: # of engineering shear components (12,...) of DDSDDE, DDSDDT, and DRPLDE
C	NTENS = NDI + NSHR: Size of the stress or strain component array

!     IN ABAQUS
!     UNIT=6 WRITES TO THE .DAT FILE
!     UNIT=7 WRITES TO THE .MSG FILE
!     WHEN DOING STEP STATIC GENERAL, 1ST CALL TO UMAT IS WITH ZERO STRAIN AND DSTRAIN
!     SO YOU HAVE TO BE CAREFUL NOT TO DIVIDE BY ZERO
!     WHEN DOING STEP LINEAR PERTURBATION, ALL CALLS TO UMAT ARE WITH ZERO DSTRAIN

!     EX 8.3
      OPEN (4,FILE='C:\SIMULIA\User\Chapter_8\Ex_8.3\PROPS.TXT')
!     TSAIW
!      OPEN (4,FILE='c:\SIMULIA\User\Chapter_3\Ex_3.14\PROPS.TXT')
!     VISCO 3D      
!      OPEN (4,FILE='c:\SIMULIA\User\Chapter_7\Ex_7.5\PROPS.TXT')
!      READ (4,*)
!      READ (4,*)
      READ(4,*) PROPS
      WRITE(6,"(/'PROPS')")
      WRITE(6,"(1PG10.3)") PROPS
      PAUSE
      
!     HERE YOU DEFINE THE STRAIN AND DELTA STRAIN YOU WANT TO PASS TO THE UMAT     
      KSTEP = 1 !EXPERIMENT WITH THIS. read abaqus documentation
      KINC = 2  !EXPERIMENT WITH THIS. read abaqus documentation
      DO I=1,NTENS
        STRAN(I) = 0.
        DSTRAN(I) = 0.
        STRESS(I) = 0.
      ENDDO
      
      DSTRAN(1) = 0.01
      DO I=1,2
      CALL UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,STRAN,DSTRAN,
     2 TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,MATERL,NDI,NSHR,NTENS,
     3 NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,CELENT,
     4 DFGRD0,DFGRD1,NOEL,NPT,KSLAY,KSPT,KSTEP,KINC)
      ENDDO
      
      WRITE(6,"(/'DDSDDE')")
      DO I=1,NTENS
        WRITE(6,2) (DDSDDE(I,J),J=1,NTENS)
      ENDDO
      WRITE(6,"(/'STRESS')")
      WRITE(6,2) STRESS
      WRITE(6,"(/'STATEV')")
      WRITE(6,2) STATEV
 2    FORMAT(1P6G10.3)
      PAUSE 'OK?'

      END
      